### ISSUE TITLE
Case behavior

### ISSUE THREAD

**Issue by tedszy** [plt/racket#1013]
Is this behavior normal? Suppose I have the following function trans. If I do (trans 's1 'e1) I get result 'foo. But if I do (trans 's1 'quote) I do not get 'goo. I get 'foo. If I put some symbol other than 'quote (such as 'q) then (trans 's1 'q) returns 'goo.

```racket
(define (trans state event)
  (case state
    ('s1 (case event
           ('e1 'foo)
           ('quote 'goo)
           ('e2 'soo)))
    ('s2 (case event
           ('e1 'bar)
           ('quote 'baz)
           ('e2 'boo)))))

**Comment by soegaard** [comment]
Yes, this is normal.

Consider:

> (case 'quote
    ['e1     'foo]
    [(quote) 'goo])
'foo

Since 'e1 is replaced by (quote e1)  by the reader, this program is the
same as:

> (case 'quote
    [(quote e1) 'foo]
    [(quote)    'goo])
'foo

So foo is returned because quote is one of the datums in the first clause.

You can write:

> (case 'quote
    [(e1) 'foo]
    [(quote) 'goo])
'goo

to get goo.



/Jens Axel






2015-08-14 18:16 GMT+02:00 Ted Szylowiec <notifications@github.com>:

> Is this behavior normal? Suppose I have the following function trans. If I
> do (trans 's1 'e1) I get result 'foo. But if I do (trans 's1 'quote) I do
> not get 'goo. I get 'foo. If I put some symbol other than 'quote (such as
> 'q) then (trans 's1 'q) returns 'goo.
>
> (define (trans state event)
> (case state
> ('s1 (case event
> ('e1 'foo)
> ('quote 'goo)
> ('e2 'soo)))
> ('s2 (case event
> ('e1 'bar)
> ('quote 'baz)
> ('e2 'boo)))))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/issues/1013>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by tedszy** [comment]
I see. I understand. Thank you.

**Comment by stamourv** [comment]
FWIW, `match` is more idiomatic than `case`. In this case, it also looks like `2dmatch` would work well.
