### ISSUE TITLE
Images are not displayed as images but as structs with `#lang htdp/bsl`

### ISSUE THREAD

**Issue by Blaisorblade** [plt/racket#1024]
On DrRacket 6.2/6.2.1 (I also think earlier), images are displayed as `#(struct:object:image% ...)` in BSL if enabled through `#lang htdp/bsl` rather than `Choose Language`. This is also well attested elsewhere, see for instance greghendershott/racket-mode#125 — I'm surprised this didn't show up already.

Screenshots from v6.2.
Broken:
<img width="1280" alt="broken" src="https://cloud.githubusercontent.com/assets/289960/9470722/83f65bdc-4b4d-11e5-86b6-1eb15d490795.png">
Working:
<img width="1280" alt="working" src="https://cloud.githubusercontent.com/assets/289960/9470721/83f035ae-4b4d-11e5-8f97-fb1147871ca5.png">

To reproduce, you can enable "Determine language from source", copy-n-paste the following in definitions and run it.

```racket
#lang htdp/bsl
(require 2htdp/image)
(circle 10 "solid" "red")
```

**Comment by Blaisorblade** [comment]
After looking *more* through Google, I found a bug report from 5 years ago:
http://users.racket-lang.narkive.com/H5koiJH7/difference-when-choosing-language-vs-lang-line

**Comment by rfindler** [comment]
Thanks for this note. This has been fixed in the pre-release build of Racket. You can download a snapshot build or build it yourself from git.

There are still lots of things wrong with `#lang htdp/bsl` and friends, tho.

Also, this is the wrong repo. You should probably be opening issues here: https://github.com/racket/htdp
